ECLK/IncidentManagement

backend/database/ec_incidents.sql
=> Adding initial DB dump

backend/database/ec_incidents.sql
=> Correcting the logic in the dump

backend/database/ec_incidents.sql, backend/src/app/main/controller/election.py, backend/src/app/main/controller/incident.py, backend/src/app/main/controller/pollingstation.py, backend/src/app/main/controller/reporter.py, backend/src/app/main/model/election.py, backend/src/app/main/model/incident.py, backend/src/app/main/model/pollingstation.py, backend/src/app/main/model/reporter.py, backend/src/app/main/service/election.py, backend/src/app/main/service/incident.py, backend/src/app/main/service/pollingstation.py, backend/src/app/main/service/reporter.py
DB dump v 000.3 and updated code with new models
=> Adding the latest models, services and controllers

backend/src/app/main/config.py, backend/src/app/main/controller/comment.py, backend/src/app/main/model/comment.py, backend/src/app/main/model/user.py
Adding all latest DB model enhancemnts
=> Adding some improvements to the model

backend/src/app/main/controller/incident_severity.py, backend/src/app/main/model/incident_severity.py, backend/src/app/main/service/incident_severity.py, backend/src/manage.py
This model will track severity settings against an incident along with history trail
=> Adding incident severity logic

backend/src/app/main/controller/incident_status.py, backend/src/app/main/model/incident_status.py, backend/src/app/main/service/incident_status.py, backend/src/manage.py
This model is about incident LCM
=> Adding model to manage lifecycle status

backend/src/app/main/controller/incident_relation.py, backend/src/app/main/model/incident_relation.py, backend/src/app/main/service/incident_relation.py, backend/src/manage.py
=> Adding support to handle related incidents

frontend/src/components/CardGrid/index.js, frontend/src/modules/landing/LandingPage.js
There were areas on the card which did not do anything even though it was shown as clickable. Therefore full card was wrapped using <Link> component, to be routed properly. 
resolved the issue #55
=> make the full card clickable.

frontend/src/data/mockapi.js, frontend/src/data/users.js, frontend/src/modules/ongoing-incidents/components/EventTrail/EventActions.js, frontend/src/modules/ongoing-incidents/components/EventTrail/StatusChange.js, frontend/src/modules/ongoing-incidents/components/IncidentView.js, frontend/src/modules/ongoing-incidents/components/ReviewIncidentListView.js, frontend/src/modules/ongoing-incidents/components/SearchForm.js, frontend/src/modules/ongoing-incidents/state/OngoingIncidents.actions.js, frontend/src/modules/ongoing-incidents/state/OngoingIncidents.reducers.js
UI enhancements to the incident search view
=> UI enhancements to the incident search view

frontend/src/modules/guest-view/components/LandingPage.js
=> sign in UI route

backend/README.md, backend/seed_data.sql, frontend/package-lock.json, frontend/src/modules/guest-view/components/LandingPage.js, frontend/src/modules/incident-filing/components/IncidentFormInternal.js, frontend/src/translation/keys/en.json, frontend/src/translation/keys/si.json, frontend/src/translation/keys/ta.json
Incident form category in all 3 languages
Intl for landing page
Data Dump for auth entities
=> Startup and intl related features

frontend/src/app/App.js, frontend/src/modules/notifications/components/ErrorNotification.js, frontend/src/modules/shared/components/DomainContainer/DomainContainer.js, frontend/src/modules/shared/components/SignInPage.js, frontend/src/modules/shared/state/Shared.actions.js
=> login bug fix

frontend/package-lock.json, frontend/package.json, frontend/src/modules/incident-filing/components/IncidentFormInternal.js, frontend/src/modules/incident-filing/components/TelephoneInput.js, frontend/src/modules/incident-filing/components/TextInputField.js
=> Create incident form validations

frontend/src/modules/ongoing-incidents/components/EventTrail/EventItem.js, frontend/src/modules/ongoing-incidents/components/EventTrail/EventItemWrapper.js
=> Event trail fix

docs/index.md
* Removed Docker Compose based commands from Local Installation section.
* Added env var initialization to UI start command example.
=> Documentation fixes

frontend/src/modules/incident-filing/components/IncidentFormInternal.js
Split the date time fields into 2.
=> added change for the splitting the date time field to two fields

frontend/src/modules/incident-filing/components/IncidentFormInternal.js
on edit, previous set date time is not shown
=> fixed issue https://github.com/ECLK/IncidentManagement/issues/406

frontend/src/incident-filing/components/IncidentFormInternal.js
=> Fix for #417

backend/seeddata/category.json
=> add inquiry catgories

backend/src/incidents/views.py, frontend/src/api/incident.js, frontend/src/app/AppLayout.js, frontend/src/app/Breadcrumbs.js, frontend/src/incident/state/incidentReducer.js, frontend/src/ongoing-incidents/components/IncidentListReview.js, frontend/src/ongoing-incidents/components/ReviewComplaintsListView.js, frontend/src/ongoing-incidents/components/ReviewInquiriesListView.js, frontend/src/ongoing-incidents/components/SearchForm.js, frontend/src/ongoing-incidents/index.js, frontend/src/routes/MainRouter.js
* Added separate view for Inquiry reviews
* Changed fields in table
* Added `incident_type` filter to backend API.
* Mapped API responses to the two views.
=> Fix for #411: Separate review screen for inquiry

frontend/src/incident/state/incidentReducer.js, frontend/src/ongoing-incidents/components/ReviewComplaintsListView.js, frontend/src/ongoing-incidents/components/ReviewInquiriesListView.js, frontend/src/ongoing-incidents/components/SearchForm.js
Fixed issues with filtering on incident review screens(#458)
=> Fixed #458: issues with filtering

frontend/package-lock.json, frontend/src/ongoing-incidents/components/EventTrail/EventActions.js
Fixed issue #474 
Handled using local state since the print request is sent without a redux action.
=> Loading spinner for print slip action

frontend/src/ongoing-incidents/components/IncidentListReview.js, frontend/src/ongoing-incidents/components/ReviewComplaintsListView.js
Changed the columns as specified in issue #480.
=> Changed columns in review list according to #480

backend/docker-compose.yml, backend/src/incidents/views.py, frontend/src/ongoing-incidents/components/IncidentListReview.js, frontend/src/ongoing-incidents/components/ReviewComplaintsListView.js, frontend/src/ongoing-incidents/components/ReviewInquiriesListView.js, frontend/src/ongoing-incidents/components/SearchForm.js, frontend/src/ongoing-incidents/components/search.js
Fixes for #461. 
* Added support for district vs institution search for complaints / inquiries.
* Re-enabled advanced search.
* Added district and institution search to backend.
=> Fix issue 461: Advanced Search

frontend/src/api/incident.js, frontend/src/ongoing-incidents/components/SearchForm.js
There was an issue in district search in complaints advanced search. Fixed it.
=> Fixed district-wise search for complaints review list

backend/docker-compose.yml, frontend/src/api/incident.js, frontend/src/ongoing-incidents/components/SearchForm.js
Fix for #409.
Mapped category as a search param going out of the frontend. The other filters were working as expected.
=> Fix for #409: Fixed issues related to search filters in incident search

frontend/src/files/components/FilePicker.js, frontend/src/ongoing-incidents/components/IncidentView.js
=> pdf upload fix - issue #532

backend/src/reporting/services.py
=> fix on main daily summary report #537
